export const projects = [
  {
    id: 1,
    title: 'Luxury — Real Estate Platform',
    slug: 'luxery-real-estate',
    description: `Luxury Real Estate Platform is a modern, full-featured real estate web application built with Next.js,React,and Tailwind CSS, focusing on a premium UI/UX, performance, and scalability. The platform delivers a high-end user experience using glassmorphic design, smooth animations, and fully responsive layouts. The application allows users to browse luxury properties, view detailed listings, manage bookings, and complete secure payments. It includes a complete authentication system, user profile management, and a role-based admin dashboard for managing properties and users. Optimized image handling via Next/Image and Cloudinary ensures fast load times and high visual quality.`,
    features: [
      'User Authentication & Authorization',
      'Property Management System',
      'Online Payment Integration',
      'User Management System',
      'Admin Dashboard',
      'Responsive Design',
      'Dark/Light Mode Toggle',
      'Role based access control',
      'Secure Payment Processing',
    ],
    challenges: [
      'Implementing Role-based Access Control',
      'Integrating Secure Payment Gateway',
      'Optimizing Database Queries',
      'Managing State Across Components',
    ],
    potentialImprovements: [
      'Add AI-powered Product Recommendations',
      'Implement Advanced Search & Filters',
      'Add Multi-language Support',
      'Enhance Mobile App Experience',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1766730045/Screenshot_From_2025-12-26_12-09-39_pv5eho.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1766730045/Screenshot_From_2025-12-26_12-09-39_pv5eho.png',
      'https://i.postimg.cc/jjBYwWdG/Screenshot-From-2025-12-26-12-09-58.png',
      'https://i.postimg.cc/GhbwyndG/Screenshot-From-2025-12-26-12-10-45.png',
      'https://i.postimg.cc/qM1Y6t19/Screenshot-From-2025-12-26-12-11-19.png',
    ],
    tech: [
      'Next.js',
      'React',
      'TailwindCSS',
      'DaisyUI',
      'TypeScript',
      'React Icons',
      'React Hot Toast',
      'SweetAlert',
      'Recharts',
      'Cloudinary',
    ],
    category: 'Full Stack Web Application',
    duration: '2.5 months',
    role: 'Full Stack Developer',
    github: 'https://github.com/HamimBhai742/Luxery-Real-Estate.git',
    live: 'https://luxery-real-estate-742.vercel.app',
  },
  {
    id: 2,
    title: 'PayWallet — Digital Wallet System',
    slug: 'paywallet-react-redux-toolkit-rtk-query',
    description:
      'PayWallet is a secure, role-based, and user-friendly frontend application designed for a Digital Wallet System (similar to bKash or Nagad). It empowers Users, Agents, and Admins to manage wallets, perform financial transactions, and monitor activities seamlessly.',
    features: [
      'Multi-role Authentication System',
      'Secure Money Transfers',
      'Transaction History & Analytics',
      'Agent Management Portal',
      'Admin Dashboard',
      'Real-time Balance Updates',
      'Mobile-first Design',
      'Transaction Notifications',
      'Dark/Light Mode Toggle',
      'Responsive Design',
      'Role-based Access Control',
    ],
    challenges: [
      'Implementing Complex State Management',
      'Ensuring Transaction Security',
      'Managing Multiple User Roles',
      'Real-time Data Synchronization',
      'Optimizing Database Queries',
    ],
    potentialImprovements: [
      'Add Multi-language Support',
      'Enhance Mobile App Experience',
      'Add AI-powered Product Recommendations',
      'Implement Advanced Search & Filters',
      'Add Multi-currency Support',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png',
      'https://i.postimg.cc/RF6KnWGC/Screenshot-From-2025-12-26-18-43-32.png',
      'https://i.postimg.cc/vHW7z6yX/Screenshot-From-2025-12-26-18-44-21.png',
      'https://i.postimg.cc/SNDRky71/Screenshot-From-2025-12-26-18-43-55.png',
    ],
    tech: [
      'React',
      'React Router',
      'Redux Toolkit',
      'RTK Query',
      'TypeScript',
      'TailwindCSS',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
      'JWT',
    ],
    category: 'Full Stack Web Application',
    duration: '2 months',
    role: 'Full Stack Developer',
    github: 'https://github.com/HamimBhai742/Assignment-06-L2',
    live: 'https://paywallet-nine.vercel.app',
  },
  {
    id: 3,
    title: 'NeXa BuY — E-commerce Platform',
    slug: 'nexa-buy-ecommerce-platform',
    description:
      'NeXa BuY is a modern, full-stack e-commerce platform built with React and Firebase. It provides a complete shopping experience with user authentication, product management, shopping cart functionality, and secure payment processing. The application features role-based access control for users, sellers, and administrators.',
    features: [
      'User Authentication & Authorization',
      'Product Management System',
      'Shopping Cart & Wishlist',
      'Secure Payment Processing',
      'Role-based Access Control',
      'Responsive Design',
      'Real-time Notifications',
      'Order Management',
      'Inventory Tracking',
      'Admin Dashboard',
      'Dark/Light Mode Toggle',
    ],
    challenges: [
      'Implementing Role-based Access Control',
      'Integrating Secure Payment Gateway',
      'Optimizing Database Queries',
      'Managing State Across Components',
    ],
    potentialImprovements: [
      'Add AI-powered Product Recommendations',
      'Implement Advanced Search & Filters',
      'Add Multi-language Support',
      'Enhance Mobile App Experience',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
      'https://i.postimg.cc/tJgTVw9c/Screenshot-From-2025-12-26-19-00-29.pnghttps://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
      'https://i.postimg.cc/d15Qv6G5/Screenshot-From-2025-12-26-18-59-43.png',
      'https://i.postimg.cc/NjRgLBR3/Screenshot-From-2025-12-26-19-02-07.png',
    ],
    tech: [
      'React',
      'React Router',
      'Node.js',
      'Express.js',
      'MongoDB',
      'JWT',
      'TailwindCSS',
      'DaisyUI',
      'Firebase',
    ],
    category: 'Front-end Web Application',
    duration: '1 months',
    role: 'Full Stack Developer',
    github: 'https://github.com/HamimBhai742/job-task-again-again',
    live: 'https://job-task-again.web.app',
  },
];
