export const projects = [
  {
    id: 1,
    title: 'NeXa BuY - E-commerce Platform',
    slug: 'nexa-buy-ecommerce-platform',
    description:
      'NeXa BuY is a modern, full-stack e-commerce platform built with React and Firebase. It provides a complete shopping experience with user authentication, product management, shopping cart functionality, and secure payment processing. The application features role-based access control for users, sellers, and administrators.',
    features: [
      'User Authentication & Authorization',
      'Product Management System',
      'Shopping Cart & Wishlist',
      'Secure Payment Processing',
      'Role-based Access Control',
      'Responsive Design',
      'Real-time Notifications',
      'Order Management',
      'Inventory Tracking',
      'Admin Dashboard',
    ],
    challenges: [
      'Implementing Role-based Access Control',
      'Integrating Secure Payment Gateway',
      'Optimizing Database Queries',
      'Managing State Across Components',
    ],
    potentialImprovements: [
      'Add AI-powered Product Recommendations',
      'Implement Advanced Search & Filters',
      'Add Multi-language Support',
      'Enhance Mobile App Experience',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759660611/qdoowour0jbfaqwq4kov.png',
    ],
    tech: [
      'React',
      'React Router',
      'Node.js',
      'Express.js',
      'MongoDB',
      'JWT',
      'TailwindCSS',
      'DaisyUI',
      'Firebase',
    ],
    category: 'Full Stack',
    duration: '3 months',
    role: 'Full Stack Developer',
    github: 'https://github.com/HamimBhai742/job-task-again-again',
    live: 'https://job-task-again.web.app',
  },
  {
    id: 2,
    title: 'PayWallet — Digital Wallet System',
    slug: 'paywallet-react-redux-toolkit-rtk-query',
    description:
      'PayWallet is a secure, role-based, and user-friendly frontend application designed for a Digital Wallet System (similar to bKash or Nagad). It empowers Users, Agents, and Admins to manage wallets, perform financial transactions, and monitor activities seamlessly.',
    features: [
      'Multi-role Authentication System',
      'Secure Money Transfers',
      'Transaction History & Analytics',
      'Agent Management Portal',
      'Admin Dashboard',
      'Real-time Balance Updates',
      'Mobile-first Design',
      'Transaction Notifications',
    ],
    challenges: [
      'Implementing Complex State Management',
      'Ensuring Transaction Security',
      'Managing Multiple User Roles',
      'Real-time Data Synchronization',
    ],
    potentialImprovements: [
      'Add Biometric Authentication',
      'Implement QR Code Payments',
      'Add Cryptocurrency Support',
      'Enhanced Analytics Dashboard',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png',
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png',
    ],
    tech: [
      'React',
      'React Router',
      'Redux Toolkit',
      'RTK Query',
      'TypeScript',
      'TailwindCSS',
      'Node.js',
      'Express.js',
      'MongoDB',
      'Mongoose',
      'JWT',
    ],
    category: 'Frontend',
    duration: '2 months',
    role: 'Frontend Developer',
    github: 'https://github.com/HamimBhai742/Assignment-06-L2',
    live: 'https://assignment-06-nine.vercel.app',
  },
  {
    id: 3,
    title: 'HireVerse - Job Management Platform',
    slug: 'job-management-platform',
    description:
      'HireVerse is a comprehensive job management platform that connects freelancers with clients. The platform allows users to post jobs, browse available opportunities, place bids, and manage their freelance business efficiently. Built with modern web technologies and featuring a stunning, responsive design.',
    features: [
      'Job Posting & Management',
      'Freelancer Profile System',
      'Bidding & Proposal System',
      'Client-Freelancer Messaging',
      'Project Timeline Tracking',
      'Payment Integration',
      'Rating & Review System',
      'Advanced Search & Filters',
    ],
    challenges: [
      'Building Complex Search Functionality',
      'Managing Real-time Communications',
      'Implementing Fair Bidding System',
      'Optimizing Performance with Large Data',
    ],
    potentialImprovements: [
      'Add Video Call Integration',
      'Implement AI Job Matching',
      'Add Portfolio Showcase',
      'Enhanced Mobile Experience',
    ],
    image:
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759644920/s08s6esw5ssdmunupajw.png',
    images: [
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759644920/s08s6esw5ssdmunupajw.png',
      'https://res.cloudinary.com/dimczn2y6/image/upload/v1759644920/s08s6esw5ssdmunupajw.png',
      ' https://res.cloudinary.com/dimczn2y6/image/upload/v1759639258/u97tmqedmzx5lt26hrfp.png'
    ],
    tech: ['React', 'React Router', 'TanStack Query', 'TailwindCSS', 'DaisyUI'],
    category: 'Frontend',
    duration: '2.5 months',
    role: 'Frontend Developer',
    github: 'https://github.com/HamimBhai742/HireVerse-client',
    live: 'https://hire-verse-client.vercel.app',
  },
];
